### ISSUE TITLE
Rotate the carousel in both directions and test servos

### ISSUE THREAD

**Issue by FTCTeam11424** [ThalesAcademyFTC/2022Training#7]

**Comment by Loaffoftoast** [comment]
easy peasy lemon sabebe

**Comment by QuinnGiffel** [comment]
ebrbrbrbrbrbrbrbrbrbrbrbrbrbrbrbrbr

**Comment by Loaffoftoast** [comment]
if (gamepad1.left_bumper) {
        robot.carouselMotor.setPower(-1);

}else if (gamepad1.right_bumper) {
        robot.carouselMotor.setPower(1);

}else   robot.carouselMotor.setPower(0);
}
}
